version: '3.1'

services:
  node:
    container_name: test_node
    image: node:14.15.1
    restart: always
    working_dir: /app
    volumes: 
      - /home/steve178/Test/express:/app
    command: tail -f /etc/hosts
  mongo:
    container_name: test_mongo
    image: mongo:4.2.11
    restart: always
    volumes: 
      - /home/steve178/Test/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root